server:
  port: ${API_GATEWAY_PORT:8081}

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/dducwsjvbe
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:dyl2509201005}
  cloud:
    gateway:
      httpclient:
        connect-timeout: ${C_TIMEOUT:5000}
        response-timeout: ${R_TIMEOUT:10000}
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=${ROUTES_USER_PATH_USER_SERVICE:/api/v1/users/**}
              metadata:
                response-timeout: ${R_TIMEOUT:10000}   # 2 giây
                connect-timeout: ${C_TIMEOUT:5000}   # 1 giây
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:10}
                    redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY:20}
                    redis-rate-limiter.requestedTokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}
            - id: user-service-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=${ROUTES_AUTH_PATH_USER_SERVICE:/api/v1/auths/**}
              metadata:
                response-timeout: ${R_TIMEOUT:10s}
                connect-timeout: ${C_TIMEOUT:5000}
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:10}
                    redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY:20}
                    redis-rate-limiter.requestedTokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}
            - id: article-service
              uri: lb://ARTICLE-SERVICE
              predicates:
                - Path=${ROUTES_PATH_ARTICLE_SERVICE:/api/v1/articles/**}
              metadata:
                response-timeout: ${R_TIMEOUT:10000}
                connect-timeout: ${C_TIMEOUT:5000}
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:10}
                    redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY:20}
                    redis-rate-limiter.requestedTokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}
            - id: file-service
              uri: lb://FILE-SERVICE
              predicates:
                - Path=${ROUTES_PATH_FILE_SERVICE:/api/v1/files/**}
              metadata:
                response-timeout: ${R_TIMEOUT:10000}
                connect-timeout: ${C_TIMEOUT:5000}
            - id: file-service-static
              uri: lb://FILE-SERVICE
              predicates:
                - Path=/uploads/**
              metadata:
                response-timeout: ${R_TIMEOUT:10000}
                connect-timeout: ${C_TIMEOUT:5000}

#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:10}
#                    redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY:20}
#                    redis-rate-limiter.requestedTokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}

eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG

#      - id: book-service
#        uri: lb://BOOK-SERVICE
#        predicates:
#          - Path=${ROUTES_PATH_BOOK_SERVICE:/api/v1/books/**}
#        filters:
#          - name: RequestRateLimiter
#            args:
#              redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:10}
#              redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY:20}
#              redis-rate-limiter.requestedTokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}
#      - id: employee-service
#        uri: lb://EMPLOYEE-SERVICE
#        predicates:
#          - Path=${ROUTES_PATH_EMPLOYEE_SERVICE:/api/v1/employees/**}
#        filters:
#          - name: RequestRateLimiter
#            args:
#              redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:10}
#              redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY:20}
#              redis-rate-limiter.requestedTokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}
#      - id: borrowing-service
#        uri: lb://BORROWING-SERVICE
#        predicates:
#          - Path=${ROUTES_PATH_BORROWING_SERVICE:/api/v1/borrowings/**}
#        filters:
#          - name: RequestRateLimiter
#            args:
#              redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:10}
#              redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY:20}
#              redis-rate-limiter.requestedTokens: ${RATE_LIMIT_REQUESTED_TOKENS:1}