server:
  port: ${FILE_SERVICE_PORT:9007}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/dducwsjvbe
  datasource:
    url: jdbc:mysql://${DB_PORT:localhost:3306}/${FILE_DB_NAME:filedb}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:dyl2509201005$}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariConnPool
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

axon:
  axonserver:
    servers: ${AXON_SERVERS:localhost:8124}

openapi:
  service:
    api-docs: File Service API
    server: ${OPENAPI_FILE_SERVER:http://localhost:9007}
    title: API Service
    version: 1.0.0

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.dducwsjvbe.file_service

idp:
  url: ${KEYCLOAK_URL:http://localhost:8180}
  client-id: ${KEYCLOAK_CLIENT_ID:dducwsjvbe_app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:WoZYF4a1w4hIPrq6laxLR28HlNqOGhcK}
  realm: ${KEYCLOAK_REALM:dducwsjvbe}

file:
  upload:
    path: ${FILE_UPLOAD_PATH:./uploads}
  temp:
    path: ${FILE_TEMP_PATH:./temp}
  chunk:
    size: 5242880
  upload-dir: ${UPLOAD_DIR:uploads/}

logging:
  logstash:
    host: ${LOGSTASH_HOST:localhost}
    port: ${LOGSTASH_PORT:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always


