spring.application.name=book-service
server.port=${BOOK_SERVICE_PORT:9001}
#eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
#db
spring.datasource.url=jdbc:mysql://${DB_PORT:localhost:3306}/${BOOK_DB_NAME:bookdb}?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:dyl2509201005$}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#axon
axon.axonserver.servers=${AXON_SERVERS:localhost:8124}
#docs
openapi.service.api-docs=Book Service API
openapi.service.server=${OPENAPI_BOOK_SERVER:http://localhost:9001}
openapi.service.title=API Service
openapi.service.version=1.0.0
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.packagesToScan=com.dducwsjvbe.book_service
#kafka
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:29092}

