spring.application.name=discovery-server
server.port=${DISCOVERY_SERVER_PORT:8761}
# No need to register with eureka server because this is the eureka server itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Disable Eureka server's own logging to reduce noise in the logs
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF